### ISSUE TITLE
PSR7 version 1.3

### ISSUE THREAD

**Issue by elvispdosreis** [google/google-auth-library-php#113]
Please add support guzzlehttp/psr7 1.3

**Comment by bshaffer** [comment]
Thanks for reporting this! Fixed in #114

**Comment by vincentwongso** [comment]
I tried installing with guzzlehttp/psr7 1.3 but it still throws the following error:

```
  Problem 1
    - Installation request for google/auth ^0.8.0 -> satisfiable by google/auth[v0.8].
    - Conclusion: remove guzzlehttp/psr7 1.3.0
    - Conclusion: don't install guzzlehttp/psr7 1.3.0
    - google/auth v0.8 requires guzzlehttp/psr7 1.2.* -> satisfiable by guzzlehttp/psr7[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - Can only install one of: guzzlehttp/psr7[1.2.0, 1.3.0].
    - Can only install one of: guzzlehttp/psr7[1.2.1, 1.3.0].
    - Can only install one of: guzzlehttp/psr7[1.2.2, 1.3.0].
    - Can only install one of: guzzlehttp/psr7[1.2.3, 1.3.0].
    - Installation request for guzzlehttp/psr7 (locked at 1.3.0) -> satisfiable by guzzlehttp/psr7[1.3.0].
```

**Comment by bshaffer** [comment]
@vincentwongso try again now, I've tagged a newer version of this library.

**Comment by vincentwongso** [comment]
awesome seems to be working fine now.

**Comment by sameerpanjwani** [comment]
Facing issue for 1.3.1

 Problem 1
   - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/
   - Installation request for google/apiclient 2.0 -> satisfiable by google/api
   - Conclusion: remove guzzlehttp/psr7 1.3.1
   - Conclusion: don't install guzzlehttp/psr7 1.3.1
   - google/auth v0.8 requires guzzlehttp/psr7 1.2.* -> satisfiable by guzzleht
   - Can only install one of: guzzlehttp/psr7[1.2.0, 1.3.1].
   - Can only install one of: guzzlehttp/psr7[1.2.1, 1.3.1].
   - Can only install one of: guzzlehttp/psr7[1.2.2, 1.3.1].
   - Can only install one of: guzzlehttp/psr7[1.2.3, 1.3.1].
   - Installation request for guzzlehttp/psr7 (locked at 1.3.1) -> satisfiable
